Repository AmericanMedicalAssociation/joe-style-guide, pull requests merged in 2019-05, with the labels that each got.

#34 EWLJ-314 design more visible links
  styleguide/source/assets/scss/01-atoms/_links.scss
Labels: in review

#39 EWLJ-410 SG - Multiple popup references to articles
  styleguide/source/_patterns/05-pages/article.twig
  styleguide/source/assets/js/resource-tooltips.js
Labels: question

#38 EWLJ-411: Read more feature request for spacing
  styleguide/source/assets/scss/02-molecules/_references.scss
  styleguide/source/assets/scss/02-molecules/_tags-list.scss
  styleguide/source/assets/scss/03-organisms/_article-footer.scss
  styleguide/source/assets/scss/05-pages/_article.scss
Labels: has D8 dependencies, ready for review

#41 EWLJ 311: theme search filter box
  styleguide/source/assets/js/filters.js
  styleguide/source/assets/scss/01-atoms/_forms.scss
  styleguide/source/assets/scss/03-organisms/_search-page-filters.scss
Labels: has D8 dependencies, ready for review

#42 Release v1.34.0
  styleguide/npm-shrinkwrap.json
  styleguide/package.json
Labels: ready for review

#44 EWLJ-441: JOE SG2 | Articles missing dates
  styleguide/source/_patterns/05-pages/article--no-image.json
Labels: ready for review

#43 EWLJ-404: Change Podcast player and height
  styleguide/source/assets/scss/01-atoms/_audio-player.scss
Labels: question

#45 EWLJ-424-add-underline-for-month/date
  styleguide/source/assets/scss/01-atoms/_flag.scss
Labels: ready for review
