Repository AmericanMedicalAssociation/joe-style-guide, pull requests merged in 2019-04, with the labels that each got.

#17 EWLJ-364 main menu broken on ipad
  styleguide/source/assets/scss/02-molecules/_utility-nav.scss
  styleguide/source/assets/scss/03-organisms/_header.scss
Labels: in review

#19 Release 1.32.0
  styleguide/npm-shrinkwrap.json
  styleguide/package.json
Labels: ready for review

#18 EWLJ-331: make homepage background transparent
  styleguide/source/assets/scss/04-templates/_offset-center.scss
Labels: ready for review

#22 EWLJ-331: add transparency to header background on homepage and issue pages
  styleguide/source/assets/scss/04-templates/_offset-center.scss
Labels: has D8 dependencies, in review

#21 EWLJ-213: Displaying flag colors when viewing articles
  styleguide/source/_patterns/01-atoms/flags.json
  styleguide/source/_patterns/05-pages/article--no-image.json
  styleguide/source/assets/scss/01-atoms/_flag.scss
Labels: has D8 dependencies, in review, question

#27 Updates version to 1.32.1
  styleguide/npm-shrinkwrap.json
  styleguide/package.json
Labels: ready for review

#24 EWLJ-373 - Regression: background of links in ribbon header a different blue
  styleguide/source/assets/scss/02-molecules/_utility-nav.scss
Labels: OK to merge, ready for review

#25 EWLJ-328 - from the archive on home page display
  styleguide/source/assets/scss/03-organisms/_topics.scss
Labels: OK to merge

#20 EWLJ-309 Adding multiselect search-sort
  styleguide/source/assets/js/filters.js
  styleguide/source/assets/scss/02-molecules/_chosen.scss
Labels: OK to merge, ready for review

#26 EWLJ-341 - tables are getting a left side gray shadow
  styleguide/source/assets/scss/01-atoms/_table.scss
Labels: OK to merge

#28 EWLJ-346: JoE | Render hero images for main navigation pages
  styleguide/source/assets/images/main-nav-pages/articles.jpg
  styleguide/source/assets/images/main-nav-pages/cases.jpg
  styleguide/source/assets/images/main-nav-pages/cme.jpg
  styleguide/source/assets/images/main-nav-pages/issues.jpg
  styleguide/source/assets/images/main-nav-pages/podcasts.jpg
  styleguide/source/assets/scss/04-templates/_offset-center.scss
Labels: OK to merge, has D8 dependencies, ready for review

#23 EWLJ-314-design-more-visible-links
  styleguide/source/assets/scss/01-atoms/_links.scss
Labels: OK to merge, ready for review

#32 EWLJ-364 - Main menu is broken on iPad
  styleguide/source/assets/scss/02-molecules/_utility-nav.scss
Labels: OK to merge

#31 Ewlj 333 integrate altmetrics
  styleguide/source/_patterns/05-pages/article.json
  styleguide/source/assets/scss/02-molecules/_article-tools.scss
Labels: has D8 dependencies, ready for review

#33 EWLJ-329: secondary navigation should sit flush right
  styleguide/source/assets/scss/02-molecules/_utility-nav.scss
  styleguide/source/assets/scss/03-organisms/_header.scss
Labels: ready for review

#36 EWLJ-326: Link from article page to issue listing page
  styleguide/source/_patterns/01-atoms/flag.json
  styleguide/source/_patterns/01-atoms/flag.twig
  styleguide/source/_patterns/01-atoms/flags.json
  styleguide/source/_patterns/02-molecules/article-header.json
  styleguide/source/_patterns/05-pages/article.json
  styleguide/source/_patterns/05-pages/podcast.json
  styleguide/source/assets/scss/01-atoms/_flag.scss
Labels: has D8 dependencies, in review

#35 EWLJ-400: Read More text needs more space under it
  styleguide/source/assets/scss/02-molecules/_issue-teaser.scss
Labels: ready for review
