Repository AmericanMedicalAssociation/joe-style-guide, pull requests merged in 2019-03, with the labels that each got.

#11 EWLJ-316: Ethics polls buttons should look the same as style guide
  styleguide/build.config.json
  styleguide/source/assets/js/poll-reveal.js
  styleguide/source/assets/scss/03-organisms/_poll.scss
Labels: has D8 dependencies, in review

#6 EWLJ-329: Secondary navigation should sit flush right
  styleguide/source/assets/scss/02-molecules/_utility-nav.scss
Labels: in review, ready for review

#8 EWLJ-324: Change line height around superscripts
  styleguide/source/assets/scss/00-base/_typography.scss
  styleguide/source/assets/scss/05-pages/_article.scss
Labels: in review

#10 EWLJ-338 Adds reference tooltip
  styleguide/build.config.json
  styleguide/source/_meta/_01-foot.twig
  styleguide/source/assets/js/resource-tooltips.js
  styleguide/source/assets/scss/00-base/_typography.scss
  styleguide/source/assets/scss/01-atoms/_tooltip.scss
Labels: has D8 dependencies, in review

#14 Ewlj 334 topic tag adjustments
  styleguide/source/_patterns/02-molecules/tags-list.twig
  styleguide/source/_patterns/05-pages/article--no-image.json
  styleguide/source/_patterns/05-pages/article--no-image.twig
  styleguide/source/_patterns/05-pages/article.twig
  styleguide/source/assets/scss/02-molecules/_tags-list.scss
Labels: has D8 dependencies, ready for review

#15 EWLJ-323: Removing CSS rules that limit the image from being displayed full size
  styleguide/source/assets/scss/02-molecules/_inline-image.scss
Labels: OK to merge
