Repository AmericanMedicalAssociation/joe-style-guide, pull requests merged in 2024-10, with the labels that each got.

#220 EWLJ-812: HotFixed article teaser arabic
  styleguide/source/assets/scss/03-organisms/_article-teaser.scss
Labels: question, in review

#224 EWLJ-830: Increased font size for Italicized text in Title on article listing page
  styleguide/source/assets/scss/01-atoms/_headings.scss
Labels: ready for review, Approval 1

#225 EWLJ-831: Spacing modifications to Read In translation text
  styleguide/source/assets/scss/05-pages/_article.scss
Labels: Approval 1

#226 EWLJ-784: Modified caption field position on Mobile devices.
  styleguide/source/assets/scss/03-organisms/_vc-layout-paragraphs.scss
Labels: OK to merge, Approval 1

#227 EWLJ-820: Art Exhibition Link in Hamburger Menu for AE/AOM/ECU Content Types
  styleguide/source/assets/scss/00-base/_slick.scss
Labels: in review, Approval 1

#231 EWLJ-765: Featured Quote-Scaling/Sizing
  styleguide/source/assets/scss/03-organisms/_vc-featured-quote.scss
Labels: ready for review

#233 EWLJ-840: Formatting of Related Articles Section on Arabic Article Page
  styleguide/source/assets/scss/00-base/_rtl.scss
Labels: Approval 1
