Repository AmericanMedicalAssociation/joe-style-guide, pull requests merged in 2024-11, with the labels that each got.

#234 EWLJ-695: Almetric badge style
  styleguide/source/assets/scss/02-molecules/_article-tools.scss
Labels: ready for review

#236 EWLJ-764: Updated tab functionality to handle multiple sets of tabs.
  styleguide/source/assets/js/vc-video-tabs.js
  styleguide/source/assets/scss/03-organisms/_vc-video-tabs.scss
Labels: ready for review, in review, OK to merge, javascript, Approval 1, approval 2

#237 EWLJ-858: style for read in links
  styleguide/source/assets/scss/05-pages/_article.scss
Labels: ready for review, OK to merge, Approval 1

#243 EWLJ-781: Ability to play Audio Files in Horizontal Gallery
  styleguide/source/assets/scss/03-organisms/_vc-horizontal-gallery.scss
Labels: OK to merge, Approval 1, approval 2
