Repository AmericanMedicalAssociation/joe-style-guide, pull requests merged in 2024-09, with the labels that each got.

#211 EWLJ-808: Fix RTL Abstract ordering in articles
  styleguide/source/assets/scss/00-base/_rtl.scss
Labels: in review

#212 EWJL-812: Style changes in Arabic articles appearing in articles page
  styleguide/source/assets/scss/03-organisms/_article-teaser.scss
Labels: ready for review

#208 EWLJ-809: Apply CSS fixes to ensure references remain left-aligned in…
  styleguide/source/assets/scss/00-base/_rtl.scss
Labels: ready for review

#209 EWLJ-763: Ensure references flow from right to left
  styleguide/source/assets/scss/00-base/_rtl.scss
Labels: question

#210 EWLJ-811: Author Information section right justified - RTL SCSS
  styleguide/source/assets/scss/00-base/_rtl.scss
Labels: Merge Conflict

#214 EWLJ-812: hotfix ar content title will use same styles as English
  styleguide/source/assets/scss/03-organisms/_article-teaser.scss
Labels: ready for review

#215 EWLJ-763: 1 - R to L Formatting Issues with Articles Translated to Arabic
  styleguide/source/assets/scss/00-base/_rtl.scss
Labels: ready for review, in review

#217 EWLJ-794: Social Media Icons on Art Exhibition Pages
  styleguide/source/assets/scss/00-base/_slick.scss
Labels: ready for review

#216 EWLJ-817: 7 - International Language Module Issues
  styleguide/source/assets/scss/00-base/_rtl.scss
Labels: ready for review

#218 EWLJ-709: Add H2 Flag Type Style Overrides
  styleguide/source/_patterns/02-molecules/wordmark.twig
  styleguide/source/assets/scss/01-atoms/_flag.scss
  styleguide/source/assets/scss/01-atoms/_headings.scss
  styleguide/source/assets/scss/02-molecules/_wordmark.scss
  styleguide/source/assets/scss/03-organisms/_vc-hero-art.scss
  styleguide/source/assets/scss/03-organisms/_vc-hero-ethics.scss
  styleguide/source/assets/scss/05-pages/_gallery.scss
Labels: ready for review
