Repository AmericanMedicalAssociation/joe-style-guide, pull requests merged in 2025-05, with the labels that each got.

#270 EWLJ-1036: Add JS to trigger nav and modified the style of header
  styleguide/source/assets/js/nav.js
  styleguide/source/assets/scss/01-atoms/_article-hero.scss
  styleguide/source/assets/scss/02-molecules/_primary-nav.scss
  styleguide/source/assets/scss/02-molecules/_utility-nav.scss
  styleguide/source/assets/scss/03-organisms/_header.scss
  styleguide/source/assets/scss/05-pages/_article.scss
Labels: OK to merge, Approval 1, approval 2

#277 EWLJ-1052: Add rule to exclude the title from the teaser reverse
  styleguide/source/assets/scss/01-atoms/_headings.scss
Labels: OK to merge, Approval 1

#267 EWLJ-1029: Styles for Topics page.
  styleguide/source/assets/icons/svg/arrow-right.svg
  styleguide/source/assets/scss/02-molecules/_page-header.scss
  styleguide/source/assets/scss/04-templates/_three-column-33-33-33.scss
Labels: ready for review, Approval 1, approval 2

#278 EWLJ-1033: Update flag color
  styleguide/source/assets/scss/05-pages/_article.scss
Labels: ready for review, OK to merge, Approval 1

#280 EWLJ-1052: Fix italic on teaser extended
  styleguide/source/assets/scss/01-atoms/_headings.scss
Labels: ready for review

#282 EWLJ-1048: Spaces for featured box on listing pages
  styleguide/source/assets/scss/01-atoms/_article-hero.scss
  styleguide/source/assets/scss/05-pages/_article.scss
Labels: ready for review, Approval 1

#285 EWLJ-1058: Reduce transition of main menu
  styleguide/source/assets/scss/03-organisms/_header.scss
Labels: ready for review, Approval 1

#283 EWLJ-1029: JOE - Create new Collections Page
  styleguide/source/assets/icons/svg/arrow-right.svg
  styleguide/source/assets/scss/04-templates/_three-column-33-33-33.scss
Labels: Approval 1, approval 2

#286 EWLJ-1059: Add rules to the sticky nav
  styleguide/source/assets/scss/02-molecules/_primary-nav.scss
Labels: ready for review, Approval 1

#290 [EWLJ-1058: Removes transition for main menu
  styleguide/source/assets/scss/03-organisms/_header.scss
Labels: ready for review, in review, Approval 1

#292 EWLJ-1029: Changed color on topics list to Navy.
  styleguide/source/assets/scss/04-templates/_three-column-33-33-33.scss
Labels: ready for review, Approval 1
